// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpvdeasneasfnvszukdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdmRlYXNuZWFzZm52c3p1a2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTAxNTAsImV4cCI6MjA3NDE2NjE1MH0.mgTw2ISeRyUgMakiv44xZfwM3LnOLEOYafOuZ3ZjaLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});